language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - npm run install
cache:
  directories:
    - "node_modules"