language: node_js
# env:
#   - CC=gcc-7 CXX=g++-7
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "12"
# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-7
#     - g++-7
cache:
  directories:
    - "node_modules"